const products = [
  {
    id: 'C001',
    category: 'Comidas',
    title: 'Pizza de Mozzarella',
    description:
      'Base de masa, salsa de tomate, queso mozarella, aceitunas y oregano.',
    price: 15000,
    imageName: 'pizza-muzzarella.jpg',
    stock: 25,
  },
  {
    id: 'C002',
    category: 'Comidas',
    title: 'Pizza de Jamón',
    description:
      'Base de masa, salsa de tomate, jamón cocido, morrones asados, queso mozzarella y aceitunas.',
    price: 15500,
    imageName: 'pizza-jamon.jpg',
    stock: 25,
  },
  {
    id: 'C003',
    category: 'Comidas',
    title: 'Hamburguesa',
    description:
      'Pan de papa, medallón de carne vacuna, lechuga, tomate, cebolla y queso tybo.',
    price: 8500,
    imageName: 'hamburguesa.jpg',
    stock: 25,
  },
  {
    id: 'C004',
    category: 'Comidas',
    title: 'Empanada de carne',
    description:
      'Masa de hojaldre, relleno de carne cortada a cuchillo, cebolla de verdeo y morrón.',
    price: 600,
    imageName: 'empanada-carne.jpg',
    stock: 25,
  },
  {
    id: 'C005',
    category: 'Comidas',
    title: 'Empanada de pollo',
    description:
      'Masa de hojaldre, relleno de pollo, cebolla de verdeo y queso.',
    price: 500,
    imageName: 'empanada-pollo.jpg',
    stock: 25,
  },
  {
    id: 'C006',
    category: 'Comidas',
    title: 'Ensalada Caesar',
    description:
      'Lechuga romana, crutones, pollo grillado y salsa a base de anchoas, huevo y queso parmesano.',
    price: 10000,
    imageName: 'ensalada-cesar.jpg',
    stock: 25,
  },
  {
    id: 'C007',
    category: 'Comidas',
    title: 'Tallarines a la Filetto',
    description:
      'Pasta fresca acompañada de salsa de tomates frescos, ajo y albahaca.',
    price: 9500,
    imageName: 'tallarines.jpg',
    stock: 25,
  },
  {
    id: 'C008',
    category: 'Comidas',
    title: 'Ravioles a la Bolognesa',
    description:
      'Pasta fresca con relleno de ricotta cubierta de salsa espesa de carne molida, tomate, zanahoria y cebolla.',
    price: 10000,
    imageName: 'ravioles.jpg',
    stock: 25,
  },
  {
    id: 'C009',
    category: 'Comidas',
    title: 'Sandwich',
    description:
      'Pan fresco relleno con rebanas de jamón cocido y queso barra, lechuga, tomate y mayonesa casera.',
    price: 5500,
    imageName: 'sandwich-jamon-queso.jpg',
    stock: 25,
  },
  {
    id: 'C010',
    category: 'Comidas',
    title: 'Lomo al plato',
    description:
      'Corte de lomo de res a la parrilla, acompañado de papas o vegetales salteados.',
    price: 12000,
    imageName: 'lomo.jpg',
    stock: 25,
  },
  {
    id: 'C011',
    category: 'Comidas',
    title: 'Milanesa',
    description:
      'Filete de carne apanado frito acompañado de puré de papas y ensalada.',
    price: 12500,
    imageName: 'milanesa.jpg',
    stock: 25,
  },
  {
    id: 'C012',
    category: 'Comidas',
    title: 'Papas fritas grandes',
    description: 'Porción de papas fritas para 2 personas.',
    price: 4000,
    imageName: 'papas-fritas-grandes.jpg',
    stock: 25,
  },
  {
    id: 'C013',
    category: 'Comidas',
    title: 'Papas fritas',
    description: 'Porción de papas fritas para 1 persona.',
    price: 2500,
    imageName: 'papas-fritas-chicas.jpg',
    stock: 25,
  },
  {
    id: 'P001',
    category: 'Postres',
    title: 'Cheesecake',
    description:
      'Porción de base de galleta crujiente, mezcla de queso y vainilla, cubierta de una capa coulis de frutos rojos.',
    price: 5000,
    imageName: 'cheesecake-frutilla.jpg',
    stock: 25,
  },
  {
    id: 'P002',
    category: 'Postres',
    title: 'Brownie de chocolate',
    description:
      'Porción de cuadrado de brownie tibio de intenso chocolate acompañado de una bola de helado de cremoso de vainilla.',
    price: 5100,
    imageName: 'brownie-helado.jpg',
    stock: 25,
  },
  {
    id: 'P003',
    category: 'Postres',
    title: 'Helado de chocolate',
    description:
      'Copa de helado de chocolate, acompañada de salsa de chocolate, virutas de chocolate y crema batida.',
    price: 3500,
    imageName: 'helado-chocolate.jpg',
    stock: 25,
  },
  {
    id: 'P004',
    category: 'Postres',
    title: 'Helado de vainilla',
    description:
      'Copa de helado de vainilla, acompañada de sirope de caramelo, nueces, crema batida y cerezas.',
    price: 3500,
    imageName: 'helado-vainilla.jpg',
    stock: 25,
  },
  {
    id: 'P005',
    category: 'Postres',
    title: 'Lemon Pie',
    description:
      'Porción de base crujiente de, capa de crema de limón suave y ligeramente ácida y una cobertura de merengue italiano.',
    price: 5100,
    imageName: 'lemon-pie.jpg',
    stock: 25,
  },
  {
    id: 'P006',
    category: 'Postres',
    title: 'Flan',
    description:
      'Porción de flan de huevo, acompañado de dulce de leche y un toque de crema batida.',
    price: 3500,
    imageName: 'flan-dulce-leche.jpg',
    stock: 25,
  },
  {
    id: 'P007',
    category: 'Postres',
    title: 'Tarta de manzana',
    description:
      'Porción de base de masa crujiente, rellena con rodajas de manzanas frescas, endulzadas y especiadas con canela.',
    price: 4500,
    imageName: 'tarta-manzana.jpg',
    stock: 25,
  },
  {
    id: 'B001',
    category: 'Bebidas',
    title: 'Gaseosa Cola',
    description: 'Gaseosa sabor cola de 1.5 litros.',
    price: 4000,
    imageName: 'gaseosa-cocacola.jpg',
    stock: 25,
  },
  {
    id: 'B002',
    category: 'Bebidas',
    title: 'Gaseosa Naranja',
    description: 'Gaseosa sabor naranja de 1.5 litros.',
    price: 4000,
    imageName: 'gaseosa-fanta.jpg',
    stock: 25,
  },
  {
    id: 'B003',
    category: 'Bebidas',
    title: 'Gaseosa Lima limón',
    description: 'Gaseosa sabor lima-limón de 1.5 litros.',
    price: 4000,
    imageName: 'gaseosa-sprite.jpg',
    stock: 25,
  },
  {
    id: 'B004',
    category: 'Bebidas',
    title: 'Cerveza',
    description: 'Cerveza de 1 litro.',
    price: 3500,
    imageName: 'cerveza.jpg',
    stock: 25,
  },
  {
    id: 'B005',
    category: 'Bebidas',
    title: 'Agua sin gas',
    description: 'Agua sin gas de 1 litro.',
    price: 3000,
    imageName: 'agua-sin-gas.jpg',
    stock: 25,
  },
  {
    id: 'B006',
    category: 'Bebidas',
    title: 'Agua con gas',
    description: 'Agua con gas de 1 litro.',
    price: 3000,
    imageName: 'agua-con-gas.jpg',
    stock: 25,
  },
  {
    id: 'B007',
    category: 'Bebidas',
    title: 'Vino Blanco',
    description: 'Copa de vino blanco.',
    price: 3000,
    imageName: 'vino-blanco.jpg',
    stock: 25,
  },
  {
    id: 'B008',
    category: 'Bebidas',
    title: 'Vino Tinto',
    description: 'Copa de vino tinto.',
    price: 3000,
    imageName: 'vino-tinto.jpg',
    stock: 25,
  },
  {
    id: 'K001',
    category: 'Cafeteria',
    title: 'Café con leche',
    description: 'Taza de café con leche.',
    price: 3000,
    imageName: 'cafe-leche.jpg',
    stock: 25,
  },
  {
    id: 'K002',
    category: 'Cafeteria',
    title: 'Café expresso',
    description: 'Taza de café expresso.',
    price: 2500,
    imageName: 'cafe-expreso.jpg',
    stock: 25,
  },
  {
    id: 'K003',
    category: 'Cafeteria',
    title: 'Té de hierbas',
    description: 'Taza de té de hierbas.',
    price: 2000,
    imageName: 'te-hierbas.jpg',
    stock: 25,
  },
  {
    id: 'K004',
    category: 'Cafeteria',
    title: 'Smoothie de chocolate',
    description: 'Batido de chocolate con leche.',
    price: 3500,
    imageName: 'batido-chocolate.jpg',
    stock: 25,
  },
  {
    id: 'K005',
    category: 'Cafeteria',
    title: 'Smoothie de frutas',
    description: 'Batido de frutas de estación con leche.',
    price: 3500,
    imageName: 'smoothie-frutas.jpg',
    stock: 25,
  },
];

const asyncMock = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(products);
    }, 2000);
  });
};

export default asyncMock;
